on: [push]

name: Code Coverage

jobs:
  grcov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
          RUSTDOCFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"

      - id: coverage-lcov
        uses: actions-rs/grcov@v0.1
        with:
          config: .github/actions/grcov-lcov.yml
      - run: mv "${{ steps.coverage-lcov.outputs.report }}" "./grcov-lcov.txt"

      # - run: bash <(curl -s https://codecov.io/bash) -f ./grcov-lcov.txt -t ${{ secrets.CODECOV_TOKEN }}

      - id: coverage-coveralls
        uses: actions-rs/grcov@v0.1
        with:
          config: .github/actions/grcov-coveralls.yml

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage-coveralls.outputs.report }}
