on: [push]

name: build-on-push

jobs:
  check:
    name: push-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: check
        with:
          command: check

      - uses: actions-rs/cargo@v1
        name: tests
        with:
          command: test
      
      - uses: actions-rs/cargo@v1
        name: formating
        with:
          command: fmt
          args: --all -- --check
    
      - uses: actions-rs/cargo@v1
        name: clippy 
        with:
          command: clippy
          args: -- -D warnings
