on: [push]

name: test-coverage

jobs:
  check:
    name: test-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: llvm-tools-preview

      - uses: actions-rs/install@v0.1
        with:
          crate: rustfilt
          version: latest
          use-tool-cache: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: latest
          use-tool-cache: true
        
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zprofile -Zinstrument-coverage -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
          RUSTDOCFLAGS: "-Zprofile -Zinstrument-coverage -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
          LLVM_PROFILE_FILE: "spds-%m.profraw"

        
      - run: cargo profdata -- merge -sparse spds-*.profraw -o spds.profdata
      
      - run: find target/debug/deps -maxdepth 1 -perm -111 -type f | xargs -0 cargo cov -- report --instr-profile=spds.profdata 
      - run: find target/debug/deps -maxdepth 1 -perm -111 -type f | xargs -0 -I % cargo cov -- show -Xdemangler=rustfilt -show-line-counts-or-regions  -show-instantiations --instr-profile=spds.profdata % > coverage-rerport.html

      - run: find target/debug/deps -maxdepth 1 -perm -111 -type f | xargs -0 -I % cargo cov -- export --instr-profile=spds.profdata -format="lcov" % > coverage-rerport.txt
      - run: bash <(curl -s https://codecov.io/bash) -f coverage-rerport.txt -t ${{ secrets.CODECOV_TOKEN }}
  
      